sudo: required

services:
  - docker

script:
  - docker build -t test:test -f Dockerfile_test .
  
after_success:
  - docker run --rm -v $(pwd)/tmp:/tmp test:test sh -c "cp -r /srv/* /tmp"
  - bash <(curl -s https://codecov.io/bash)
